{% set name = "datasette-edit-schema" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datasette-edit-schema-{{ version }}.tar.gz
  sha256: e7de83533bbb441ed0f392b2cae9a2871931be917f69cbad1d60c79cac1dbe08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - datasette >=0.63
    - sqlite-utils >=3.35

test:
  imports:
    - datasette_edit_schema
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simonw/datasette-edit-schema
  summary: Datasette plugin for modifying table schemas
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
